CREATE TABLE hotel_feedback(
   id       INTEGER  NOT NULL PRIMARY KEY AUTO_INCREMENT
  ,stars    INTEGER  NOT NULL
  ,review   VARCHAR(9) NOT NULL
  ,cust_id  INTEGER  NOT NULL
  ,hotel_id INTEGER  NOT NULL
  ,FOREIGN KEY (hotel_id) REFERENCES hotel(id)
  ,FOREIGN KEY (cust_id) REFERENCES customer(id)
  ,CONSTRAINT CHK_Stars CHECK (stars>=1 AND stars<=5)

);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (1,3,'Bad',66,1);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (2,4,'Very Good',85,2);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (3,3,'Bad',42,3);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (4,4,'Very Good',54,4);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (5,1,'Excellent',58,5);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (6,1,'Very Bad',24,6);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (7,2,'Very Good',4,7);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (8,3,'Average',44,8);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (9,5,'Very Bad',17,9);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (10,3,'Bad',30,10);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (11,3,'Average',63,11);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (12,4,'Average',20,12);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (13,1,'Excellent',59,13);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (14,2,'Good',60,14);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (15,1,'Average',7,15);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (16,1,'Average',44,16);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (17,3,'Good',19,17);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (18,2,'Excellent',3,18);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (19,4,'Average',99,19);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (20,1,'Very Good',37,20);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (21,1,'Very Bad',33,21);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (22,5,'Very Bad',40,22);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (23,4,'Very Good',80,23);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (24,2,'Bad',95,24);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (25,2,'Very Bad',98,25);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (26,2,'Very Good',64,26);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (27,3,'Bad',40,27);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (28,5,'Bad',90,28);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (29,4,'Good',59,29);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (30,3,'Average',81,30);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (31,3,'Bad',88,31);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (32,3,'Bad',16,32);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (33,1,'Very Bad',29,33);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (34,1,'Bad',37,34);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (35,2,'Average',42,35);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (36,1,'Average',80,36);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (37,3,'Very Good',25,37);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (38,1,'Very Bad',41,38);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (39,3,'Excellent',45,39);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (40,5,'Very Bad',69,40);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (41,3,'Very Good',21,41);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (42,4,'Very Bad',15,42);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (43,5,'Good',43,43);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (44,3,'Very Good',63,44);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (45,3,'Very Bad',21,45);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (46,3,'Bad',63,46);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (47,1,'Excellent',53,47);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (48,3,'Excellent',4,48);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (49,5,'Bad',73,49);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (50,3,'Good',48,50);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (51,4,'Very Good',81,51);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (52,4,'Very Bad',43,52);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (53,5,'Very Good',8,53);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (54,2,'Excellent',3,54);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (55,3,'Excellent',45,55);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (56,5,'Good',80,56);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (57,5,'Very Good',58,57);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (58,3,'Very Good',23,58);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (59,1,'Very Bad',48,59);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (60,4,'Good',32,60);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (61,5,'Average',67,61);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (62,4,'Good',56,62);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (63,1,'Bad',46,63);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (64,2,'Very Good',62,64);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (65,3,'Bad',55,65);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (66,1,'Average',51,66);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (67,5,'Excellent',13,67);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (68,2,'Very Good',75,68);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (69,1,'Good',34,69);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (70,4,'Good',99,70);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (71,3,'Bad',74,71);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (72,5,'Average',55,72);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (73,1,'Bad',33,73);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (74,1,'Excellent',39,74);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (75,3,'Very Bad',43,75);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (76,5,'Excellent',6,76);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (77,1,'Very Good',80,77);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (78,4,'Very Bad',23,78);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (79,4,'Bad',11,79);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (80,2,'Very Bad',42,80);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (81,5,'Excellent',15,81);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (82,1,'Very Good',1,82);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (83,5,'Very Good',13,83);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (84,3,'Very Good',37,84);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (85,4,'Very Good',24,85);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (86,5,'Very Bad',41,86);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (87,4,'Excellent',27,87);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (88,1,'Very Good',84,88);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (89,3,'Very Good',42,89);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (90,3,'Good',16,90);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (91,4,'Very Good',74,91);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (92,5,'Excellent',71,92);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (93,3,'Very Good',16,93);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (94,2,'Excellent',22,94);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (95,3,'Good',33,95);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (96,2,'Very Good',89,96);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (97,2,'Bad',34,97);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (98,2,'Bad',91,98);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (99,1,'Very Bad',71,99);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (100,1,'Very Bad',61,100);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (101,4,'Very Bad',77,1);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (102,3,'Very Bad',6,2);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (103,4,'Very Bad',62,3);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (104,3,'Very Bad',97,4);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (105,4,'Good',27,5);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (106,1,'Average',34,6);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (107,4,'Excellent',4,7);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (108,3,'Very Bad',7,8);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (109,3,'Very Good',89,9);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (110,5,'Very Good',33,10);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (111,3,'Average',26,11);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (112,4,'Very Good',14,12);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (113,1,'Very Bad',45,13);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (114,5,'Bad',85,14);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (115,5,'Very Bad',78,15);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (116,1,'Good',20,16);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (117,3,'Average',83,17);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (118,2,'Very Bad',5,18);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (119,1,'Good',66,19);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (120,5,'Good',78,20);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (121,2,'Bad',56,21);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (122,5,'Very Good',62,22);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (123,4,'Good',17,23);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (124,2,'Very Good',32,24);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (125,5,'Bad',15,25);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (126,1,'Average',53,26);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (127,5,'Average',100,27);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (128,1,'Bad',67,28);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (129,3,'Average',75,29);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (130,1,'Good',54,30);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (131,5,'Very Bad',31,31);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (132,3,'Average',45,32);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (133,2,'Bad',55,33);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (134,1,'Excellent',61,34);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (135,5,'Good',82,35);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (136,5,'Average',65,36);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (137,4,'Very Bad',100,37);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (138,3,'Very Good',56,38);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (139,1,'Very Good',80,39);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (140,1,'Excellent',24,40);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (141,3,'Excellent',34,41);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (142,3,'Bad',89,42);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (143,3,'Very Bad',5,43);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (144,3,'Very Good',44,44);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (145,4,'Very Bad',22,45);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (146,1,'Very Good',14,46);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (147,1,'Excellent',76,47);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (148,2,'Bad',31,48);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (149,5,'Bad',35,49);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (150,1,'Excellent',73,50);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (151,4,'Very Bad',99,51);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (152,3,'Good',60,52);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (153,1,'Very Bad',57,53);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (154,5,'Excellent',5,54);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (155,2,'Excellent',19,55);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (156,5,'Very Bad',98,56);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (157,5,'Average',58,57);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (158,3,'Very Bad',31,58);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (159,5,'Very Good',53,59);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (160,2,'Good',26,60);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (161,4,'Average',34,61);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (162,2,'Very Bad',26,62);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (163,3,'Bad',71,63);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (164,2,'Good',8,64);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (165,3,'Good',38,65);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (166,2,'Bad',25,66);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (167,3,'Good',49,67);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (168,1,'Bad',5,68);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (169,1,'Excellent',60,69);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (170,5,'Excellent',93,70);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (171,5,'Excellent',8,71);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (172,3,'Very Bad',85,72);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (173,2,'Bad',58,73);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (174,4,'Good',58,74);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (175,1,'Excellent',73,75);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (176,5,'Very Bad',40,76);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (177,4,'Very Good',63,77);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (178,4,'Excellent',52,78);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (179,5,'Good',51,79);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (180,5,'Very Good',75,80);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (181,4,'Good',48,81);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (182,2,'Very Good',54,82);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (183,5,'Very Bad',61,83);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (184,1,'Bad',68,84);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (185,4,'Good',84,85);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (186,4,'Very Bad',58,86);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (187,3,'Very Good',83,87);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (188,3,'Excellent',34,88);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (189,4,'Good',43,89);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (190,5,'Bad',40,90);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (191,2,'Good',92,91);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (192,4,'Very Good',92,92);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (193,5,'Very Bad',86,93);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (194,4,'Bad',85,94);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (195,5,'Good',10,95);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (196,3,'Very Bad',49,96);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (197,4,'Very Good',40,97);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (198,3,'Average',42,98);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (199,5,'Excellent',76,99);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (200,5,'Very Bad',15,100);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (201,2,'Average',55,1);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (202,2,'Average',21,2);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (203,4,'Very Good',8,3);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (204,1,'Average',89,4);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (205,4,'Excellent',81,5);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (206,3,'Very Bad',25,6);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (207,2,'Very Good',65,7);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (208,5,'Very Good',17,8);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (209,1,'Excellent',44,9);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (210,3,'Bad',97,10);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (211,2,'Very Good',22,11);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (212,1,'Very Bad',34,12);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (213,5,'Average',65,13);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (214,1,'Average',55,14);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (215,4,'Very Bad',25,15);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (216,1,'Good',11,16);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (217,4,'Good',36,17);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (218,1,'Average',99,18);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (219,3,'Average',96,19);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (220,5,'Excellent',23,20);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (221,3,'Average',2,21);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (222,2,'Bad',62,22);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (223,2,'Very Good',22,23);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (224,5,'Excellent',34,24);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (225,1,'Good',61,25);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (226,5,'Very Good',2,26);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (227,1,'Very Bad',24,27);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (228,5,'Good',45,28);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (229,2,'Very Good',97,29);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (230,4,'Bad',27,30);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (231,1,'Very Good',66,31);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (232,2,'Very Bad',49,32);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (233,3,'Excellent',16,33);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (234,3,'Very Bad',37,34);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (235,4,'Excellent',20,35);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (236,1,'Excellent',60,36);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (237,5,'Very Bad',39,37);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (238,2,'Average',9,38);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (239,5,'Very Bad',26,39);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (240,1,'Excellent',33,40);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (241,4,'Excellent',73,41);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (242,5,'Average',18,42);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (243,4,'Average',27,43);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (244,5,'Average',7,44);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (245,5,'Very Bad',62,45);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (246,5,'Bad',38,46);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (247,1,'Average',27,47);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (248,1,'Excellent',22,48);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (249,5,'Good',44,49);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (250,3,'Very Good',58,50);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (251,3,'Very Good',44,51);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (252,3,'Average',42,52);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (253,5,'Excellent',6,53);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (254,1,'Very Bad',67,54);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (255,5,'Good',63,55);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (256,1,'Average',60,56);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (257,5,'Very Good',9,57);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (258,4,'Very Good',85,58);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (259,1,'Very Bad',1,59);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (260,3,'Average',35,60);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (261,1,'Very Bad',23,61);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (262,1,'Very Good',65,62);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (263,2,'Excellent',60,63);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (264,3,'Bad',88,64);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (265,1,'Bad',100,65);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (266,1,'Average',60,66);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (267,4,'Good',97,67);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (268,2,'Bad',31,68);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (269,5,'Excellent',37,69);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (270,3,'Excellent',96,70);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (271,2,'Bad',79,71);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (272,1,'Very Good',18,72);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (273,2,'Good',13,73);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (274,5,'Very Bad',4,74);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (275,1,'Average',69,75);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (276,1,'Excellent',3,76);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (277,1,'Average',95,77);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (278,5,'Bad',76,78);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (279,1,'Average',74,79);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (280,5,'Very Bad',91,80);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (281,1,'Very Bad',45,81);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (282,1,'Excellent',33,82);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (283,5,'Very Good',38,83);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (284,2,'Average',62,84);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (285,3,'Very Bad',54,85);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (286,5,'Very Good',87,86);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (287,2,'Good',98,87);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (288,3,'Very Bad',34,88);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (289,5,'Average',43,89);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (290,1,'Very Bad',26,90);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (291,4,'Very Bad',5,91);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (292,1,'Average',35,92);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (293,4,'Very Bad',20,93);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (294,5,'Bad',32,94);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (295,3,'Good',33,95);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (296,4,'Good',60,96);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (297,4,'Excellent',3,97);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (298,3,'Bad',10,98);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (299,1,'Very Good',45,99);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (300,4,'Very Bad',85,100);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (301,3,'Very Bad',98,1);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (302,2,'Bad',80,2);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (303,1,'Good',81,3);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (304,4,'Excellent',78,4);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (305,2,'Very Bad',41,5);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (306,3,'Average',74,6);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (307,2,'Average',24,7);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (308,3,'Bad',21,8);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (309,3,'Very Good',72,9);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (310,5,'Very Bad',20,10);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (311,2,'Very Good',87,11);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (312,1,'Excellent',11,12);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (313,3,'Very Good',27,13);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (314,2,'Excellent',54,14);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (315,2,'Very Good',22,15);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (316,2,'Good',83,16);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (317,2,'Average',65,17);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (318,1,'Excellent',19,18);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (319,1,'Excellent',28,19);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (320,2,'Very Bad',72,20);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (321,4,'Good',58,21);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (322,2,'Excellent',85,22);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (323,5,'Very Bad',80,23);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (324,5,'Bad',42,24);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (325,5,'Very Good',35,25);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (326,5,'Very Good',51,26);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (327,2,'Very Good',78,27);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (328,2,'Excellent',97,28);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (329,5,'Bad',9,29);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (330,5,'Very Bad',83,30);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (331,3,'Very Good',77,31);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (332,1,'Very Bad',14,32);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (333,5,'Bad',35,33);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (334,2,'Very Bad',49,34);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (335,5,'Average',91,35);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (336,5,'Good',43,36);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (337,3,'Excellent',38,37);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (338,1,'Very Good',36,38);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (339,5,'Average',68,39);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (340,3,'Very Bad',6,40);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (341,2,'Very Bad',46,41);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (342,4,'Very Bad',47,42);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (343,4,'Very Good',45,43);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (344,2,'Bad',98,44);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (345,1,'Very Bad',97,45);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (346,4,'Good',36,46);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (347,2,'Very Bad',36,47);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (348,2,'Good',90,48);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (349,1,'Average',12,49);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (350,3,'Good',87,50);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (351,5,'Bad',92,51);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (352,3,'Very Bad',94,52);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (353,4,'Very Bad',12,53);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (354,2,'Very Bad',31,54);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (355,5,'Average',34,55);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (356,2,'Very Good',79,56);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (357,1,'Excellent',61,57);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (358,5,'Bad',51,58);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (359,3,'Good',59,59);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (360,3,'Average',15,60);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (361,4,'Average',69,61);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (362,1,'Very Bad',71,62);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (363,5,'Very Good',58,63);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (364,4,'Bad',3,64);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (365,5,'Average',18,65);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (366,2,'Very Bad',100,66);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (367,3,'Good',50,67);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (368,1,'Excellent',83,68);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (369,5,'Very Good',13,69);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (370,3,'Bad',14,70);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (371,4,'Very Good',81,71);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (372,2,'Excellent',12,72);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (373,2,'Good',64,73);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (374,5,'Excellent',77,74);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (375,4,'Excellent',92,75);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (376,1,'Average',92,76);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (377,3,'Good',73,77);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (378,1,'Good',76,78);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (379,5,'Very Good',80,79);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (380,3,'Average',38,80);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (381,4,'Average',9,81);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (382,4,'Very Bad',31,82);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (383,3,'Very Good',58,83);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (384,2,'Good',60,84);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (385,2,'Average',51,85);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (386,3,'Very Good',19,86);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (387,5,'Average',55,87);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (388,4,'Very Bad',11,88);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (389,5,'Bad',73,89);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (390,5,'Very Good',44,90);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (391,4,'Good',91,91);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (392,3,'Average',74,92);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (393,1,'Excellent',61,93);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (394,3,'Very Bad',42,94);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (395,4,'Good',94,95);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (396,3,'Average',15,96);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (397,3,'Very Good',69,97);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (398,2,'Very Good',13,98);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (399,2,'Excellent',1,99);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (400,5,'Good',64,100);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (401,5,'Excellent',45,1);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (402,5,'Good',80,2);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (403,5,'Very Good',99,3);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (404,2,'Excellent',10,4);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (405,1,'Good',39,5);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (406,3,'Bad',18,6);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (407,5,'Excellent',6,7);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (408,1,'Very Good',8,8);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (409,5,'Excellent',77,9);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (410,5,'Good',28,10);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (411,5,'Average',70,11);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (412,3,'Very Bad',79,12);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (413,2,'Very Bad',35,13);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (414,4,'Good',18,14);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (415,2,'Very Good',92,15);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (416,1,'Very Bad',65,16);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (417,4,'Bad',96,17);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (418,2,'Average',16,18);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (419,4,'Average',27,19);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (420,4,'Average',17,20);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (421,4,'Average',19,21);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (422,4,'Good',49,22);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (423,4,'Bad',38,23);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (424,5,'Excellent',54,24);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (425,1,'Bad',31,25);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (426,5,'Bad',77,26);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (427,3,'Excellent',3,27);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (428,2,'Excellent',63,28);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (429,5,'Bad',3,29);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (430,3,'Very Good',8,30);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (431,4,'Average',77,31);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (432,3,'Excellent',35,32);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (433,5,'Very Bad',12,33);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (434,3,'Average',50,34);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (435,2,'Bad',42,35);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (436,5,'Very Good',97,36);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (437,1,'Bad',33,37);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (438,4,'Very Good',85,38);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (439,3,'Good',16,39);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (440,2,'Very Bad',32,40);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (441,2,'Bad',70,41);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (442,4,'Very Good',82,42);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (443,1,'Good',86,43);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (444,1,'Excellent',50,44);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (445,2,'Very Bad',14,45);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (446,4,'Very Bad',45,46);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (447,5,'Bad',67,47);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (448,3,'Bad',63,48);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (449,2,'Average',15,49);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (450,5,'Very Good',88,50);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (451,1,'Excellent',30,51);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (452,4,'Excellent',69,52);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (453,1,'Bad',67,53);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (454,5,'Very Good',51,54);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (455,3,'Excellent',93,55);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (456,3,'Very Bad',26,56);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (457,3,'Excellent',72,57);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (458,5,'Very Good',42,58);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (459,5,'Good',51,59);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (460,1,'Very Good',70,60);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (461,3,'Bad',81,61);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (462,3,'Bad',48,62);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (463,5,'Very Good',86,63);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (464,4,'Very Good',4,64);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (465,1,'Very Good',60,65);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (466,1,'Excellent',29,66);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (467,5,'Very Good',62,67);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (468,3,'Average',40,68);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (469,3,'Good',12,69);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (470,2,'Average',46,70);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (471,5,'Very Good',61,71);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (472,4,'Excellent',31,72);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (473,1,'Very Good',36,73);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (474,3,'Very Bad',72,74);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (475,4,'Good',40,75);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (476,2,'Very Bad',6,76);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (477,5,'Very Good',3,77);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (478,1,'Average',15,78);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (479,4,'Average',74,79);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (480,5,'Average',96,80);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (481,1,'Very Good',51,81);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (482,5,'Good',3,82);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (483,1,'Excellent',68,83);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (484,2,'Very Bad',36,84);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (485,2,'Very Good',61,85);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (486,4,'Excellent',50,86);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (487,2,'Average',20,87);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (488,5,'Very Bad',72,88);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (489,5,'Excellent',23,89);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (490,4,'Average',87,90);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (491,2,'Bad',12,91);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (492,3,'Very Good',81,92);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (493,3,'Excellent',74,93);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (494,3,'Bad',42,94);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (495,5,'Very Bad',7,95);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (496,4,'Bad',79,96);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (497,3,'Good',15,97);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (498,5,'Average',20,98);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (499,1,'Excellent',8,99);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (500,2,'Very Bad',88,100);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (501,5,'Excellent',59,1);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (502,1,'Very Good',39,2);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (503,2,'Bad',74,3);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (504,2,'Bad',28,4);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (505,4,'Average',98,5);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (506,5,'Excellent',36,6);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (507,5,'Very Bad',16,7);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (508,1,'Excellent',72,8);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (509,3,'Bad',85,9);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (510,2,'Bad',50,10);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (511,1,'Average',14,11);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (512,2,'Very Good',13,12);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (513,1,'Good',14,13);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (514,4,'Bad',7,14);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (515,2,'Very Bad',37,15);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (516,2,'Bad',77,16);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (517,4,'Bad',14,17);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (518,2,'Good',89,18);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (519,2,'Very Bad',78,19);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (520,2,'Bad',58,20);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (521,5,'Average',10,21);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (522,2,'Good',71,22);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (523,3,'Bad',28,23);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (524,2,'Excellent',63,24);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (525,2,'Good',38,25);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (526,3,'Good',73,26);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (527,3,'Average',33,27);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (528,4,'Very Good',7,28);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (529,4,'Excellent',25,29);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (530,4,'Bad',47,30);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (531,3,'Excellent',78,31);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (532,1,'Very Good',19,32);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (533,1,'Good',63,33);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (534,4,'Good',54,34);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (535,1,'Excellent',54,35);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (536,4,'Average',48,36);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (537,2,'Average',50,37);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (538,3,'Average',49,38);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (539,4,'Excellent',62,39);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (540,3,'Very Good',75,40);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (541,2,'Excellent',20,41);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (542,5,'Very Good',15,42);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (543,2,'Good',46,43);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (544,5,'Bad',43,44);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (545,5,'Very Good',90,45);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (546,1,'Good',85,46);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (547,1,'Average',53,47);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (548,3,'Very Bad',61,48);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (549,4,'Good',73,49);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (550,4,'Very Good',29,50);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (551,5,'Good',67,51);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (552,5,'Average',65,52);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (553,4,'Very Bad',7,53);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (554,3,'Very Good',66,54);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (555,4,'Average',65,55);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (556,4,'Bad',84,56);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (557,5,'Excellent',45,57);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (558,5,'Bad',42,58);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (559,2,'Very Good',27,59);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (560,1,'Average',42,60);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (561,2,'Excellent',96,61);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (562,3,'Bad',30,62);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (563,2,'Bad',49,63);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (564,5,'Very Good',88,64);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (565,2,'Bad',7,65);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (566,4,'Good',64,66);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (567,4,'Average',35,67);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (568,2,'Excellent',60,68);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (569,1,'Good',50,69);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (570,2,'Average',64,70);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (571,1,'Good',50,71);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (572,4,'Very Good',12,72);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (573,5,'Very Good',37,73);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (574,2,'Bad',61,74);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (575,3,'Average',68,75);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (576,2,'Very Good',36,76);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (577,3,'Very Good',92,77);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (578,5,'Good',78,78);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (579,1,'Good',69,79);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (580,3,'Bad',91,80);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (581,5,'Average',23,81);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (582,3,'Excellent',97,82);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (583,2,'Excellent',56,83);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (584,5,'Very Bad',54,84);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (585,3,'Very Bad',99,85);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (586,2,'Bad',88,86);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (587,5,'Average',73,87);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (588,3,'Bad',57,88);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (589,5,'Very Good',76,89);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (590,5,'Average',37,90);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (591,3,'Excellent',77,91);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (592,4,'Very Bad',91,92);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (593,1,'Average',2,93);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (594,2,'Excellent',65,94);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (595,3,'Excellent',57,95);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (596,1,'Excellent',17,96);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (597,5,'Very Bad',95,97);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (598,1,'Bad',60,98);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (599,2,'Bad',21,99);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (600,3,'Excellent',10,100);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (601,2,'Bad',39,1);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (602,3,'Very Good',83,2);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (603,3,'Average',16,3);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (604,3,'Average',90,4);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (605,3,'Excellent',58,5);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (606,5,'Bad',58,6);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (607,3,'Average',84,7);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (608,3,'Average',97,8);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (609,2,'Good',23,9);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (610,2,'Average',73,10);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (611,1,'Bad',27,11);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (612,5,'Average',83,12);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (613,3,'Very Good',55,13);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (614,3,'Average',94,14);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (615,1,'Bad',9,15);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (616,4,'Bad',47,16);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (617,2,'Excellent',46,17);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (618,1,'Good',6,18);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (619,3,'Very Bad',42,19);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (620,1,'Average',53,20);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (621,1,'Average',29,21);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (622,3,'Excellent',10,22);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (623,5,'Good',61,23);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (624,1,'Very Bad',37,24);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (625,4,'Excellent',12,25);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (626,3,'Very Bad',28,26);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (627,3,'Very Bad',82,27);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (628,2,'Very Good',94,28);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (629,2,'Average',27,29);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (630,3,'Very Good',11,30);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (631,2,'Bad',33,31);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (632,5,'Average',27,32);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (633,3,'Good',36,33);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (634,3,'Good',15,34);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (635,2,'Good',36,35);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (636,1,'Very Bad',1,36);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (637,5,'Very Bad',57,37);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (638,2,'Good',35,38);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (639,3,'Very Good',87,39);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (640,2,'Good',6,40);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (641,3,'Very Bad',69,41);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (642,3,'Very Bad',70,42);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (643,4,'Bad',36,43);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (644,5,'Bad',22,44);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (645,2,'Good',25,45);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (646,5,'Very Bad',64,46);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (647,5,'Excellent',65,47);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (648,1,'Good',9,48);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (649,2,'Good',7,49);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (650,2,'Very Bad',30,50);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (651,5,'Excellent',79,51);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (652,5,'Bad',69,52);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (653,1,'Excellent',71,53);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (654,1,'Very Bad',28,54);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (655,4,'Bad',60,55);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (656,5,'Very Bad',70,56);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (657,3,'Excellent',14,57);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (658,2,'Bad',20,58);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (659,1,'Very Good',45,59);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (660,3,'Bad',15,60);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (661,3,'Very Good',36,61);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (662,5,'Very Bad',13,62);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (663,4,'Good',62,63);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (664,4,'Excellent',95,64);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (665,4,'Very Bad',39,65);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (666,1,'Bad',41,66);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (667,5,'Very Bad',86,67);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (668,5,'Average',14,68);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (669,3,'Bad',70,69);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (670,2,'Bad',39,70);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (671,2,'Bad',100,71);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (672,5,'Very Good',87,72);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (673,2,'Very Bad',72,73);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (674,4,'Very Good',69,74);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (675,1,'Bad',100,75);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (676,5,'Average',11,76);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (677,1,'Bad',33,77);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (678,3,'Good',59,78);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (679,4,'Average',21,79);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (680,3,'Excellent',72,80);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (681,1,'Good',79,81);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (682,3,'Excellent',18,82);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (683,1,'Bad',55,83);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (684,2,'Excellent',84,84);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (685,5,'Very Good',15,85);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (686,1,'Bad',92,86);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (687,5,'Good',36,87);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (688,5,'Excellent',8,88);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (689,3,'Very Bad',24,89);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (690,5,'Very Bad',83,90);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (691,1,'Average',56,91);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (692,3,'Average',17,92);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (693,5,'Very Good',69,93);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (694,1,'Very Bad',93,94);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (695,5,'Very Good',41,95);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (696,3,'Bad',82,96);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (697,3,'Good',46,97);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (698,5,'Very Good',88,98);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (699,3,'Good',62,99);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (700,3,'Very Good',16,100);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (701,5,'Excellent',35,1);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (702,2,'Good',27,2);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (703,2,'Average',4,3);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (704,5,'Bad',23,4);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (705,5,'Bad',61,5);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (706,2,'Very Bad',26,6);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (707,4,'Excellent',88,7);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (708,2,'Very Good',87,8);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (709,1,'Excellent',87,9);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (710,3,'Very Bad',6,10);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (711,1,'Average',4,11);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (712,5,'Very Good',56,12);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (713,2,'Very Good',27,13);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (714,2,'Bad',25,14);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (715,2,'Very Bad',96,15);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (716,1,'Average',58,16);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (717,3,'Good',99,17);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (718,2,'Very Bad',21,18);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (719,4,'Very Bad',1,19);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (720,5,'Very Good',52,20);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (721,5,'Excellent',77,21);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (722,5,'Very Bad',23,22);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (723,1,'Excellent',92,23);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (724,5,'Very Bad',72,24);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (725,4,'Average',98,25);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (726,2,'Average',8,26);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (727,5,'Very Good',22,27);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (728,3,'Very Bad',36,28);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (729,5,'Average',6,29);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (730,1,'Bad',84,30);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (731,5,'Excellent',21,31);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (732,3,'Good',12,32);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (733,1,'Average',66,33);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (734,1,'Good',99,34);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (735,3,'Bad',3,35);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (736,1,'Bad',68,36);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (737,1,'Very Good',36,37);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (738,2,'Excellent',81,38);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (739,1,'Good',14,39);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (740,5,'Bad',97,40);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (741,3,'Average',40,41);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (742,5,'Average',90,42);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (743,1,'Good',47,43);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (744,2,'Very Bad',16,44);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (745,1,'Excellent',80,45);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (746,1,'Good',19,46);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (747,5,'Excellent',25,47);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (748,4,'Very Bad',64,48);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (749,4,'Very Bad',82,49);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (750,5,'Excellent',8,50);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (751,1,'Good',54,51);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (752,1,'Excellent',14,52);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (753,2,'Very Bad',66,53);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (754,1,'Good',79,54);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (755,5,'Very Bad',50,55);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (756,2,'Excellent',14,56);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (757,5,'Bad',23,57);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (758,2,'Very Good',50,58);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (759,5,'Average',64,59);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (760,4,'Average',40,60);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (761,4,'Very Good',31,61);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (762,2,'Average',65,62);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (763,3,'Average',57,63);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (764,5,'Very Good',69,64);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (765,4,'Very Bad',26,65);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (766,4,'Good',83,66);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (767,1,'Excellent',88,67);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (768,5,'Excellent',49,68);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (769,3,'Average',97,69);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (770,5,'Very Good',55,70);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (771,5,'Good',84,71);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (772,5,'Bad',38,72);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (773,5,'Very Bad',7,73);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (774,3,'Excellent',30,74);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (775,1,'Very Good',13,75);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (776,4,'Average',62,76);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (777,5,'Very Bad',85,77);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (778,1,'Very Good',24,78);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (779,2,'Very Good',1,79);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (780,5,'Bad',29,80);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (781,3,'Excellent',80,81);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (782,2,'Average',45,82);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (783,2,'Very Bad',68,83);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (784,2,'Very Bad',90,84);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (785,4,'Very Bad',63,85);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (786,5,'Average',79,86);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (787,5,'Good',36,87);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (788,5,'Very Good',77,88);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (789,3,'Good',77,89);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (790,1,'Average',82,90);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (791,4,'Excellent',36,91);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (792,2,'Average',92,92);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (793,2,'Average',72,93);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (794,2,'Bad',95,94);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (795,2,'Very Bad',43,95);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (796,1,'Bad',27,96);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (797,2,'Very Good',100,97);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (798,2,'Bad',38,98);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (799,2,'Bad',96,99);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (800,1,'Bad',57,100);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (801,2,'Bad',75,1);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (802,2,'Very Good',27,2);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (803,1,'Very Good',28,3);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (804,2,'Very Good',52,4);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (805,3,'Excellent',61,5);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (806,3,'Bad',51,6);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (807,4,'Bad',67,7);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (808,5,'Excellent',41,8);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (809,4,'Very Good',9,9);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (810,2,'Bad',49,10);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (811,5,'Excellent',86,11);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (812,5,'Bad',50,12);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (813,5,'Bad',98,13);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (814,3,'Excellent',11,14);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (815,3,'Average',79,15);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (816,5,'Very Bad',4,16);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (817,1,'Very Bad',28,17);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (818,4,'Very Bad',15,18);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (819,4,'Bad',40,19);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (820,5,'Bad',77,20);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (821,1,'Very Bad',3,21);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (822,2,'Very Bad',61,22);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (823,2,'Average',29,23);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (824,1,'Bad',87,24);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (825,3,'Very Good',75,25);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (826,2,'Good',15,26);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (827,1,'Bad',31,27);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (828,5,'Very Good',3,28);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (829,2,'Very Good',58,29);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (830,5,'Excellent',13,30);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (831,4,'Average',98,31);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (832,5,'Excellent',54,32);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (833,5,'Average',15,33);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (834,1,'Average',68,34);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (835,3,'Very Bad',83,35);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (836,4,'Bad',82,36);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (837,2,'Excellent',52,37);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (838,1,'Average',85,38);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (839,3,'Excellent',49,39);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (840,4,'Bad',76,40);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (841,5,'Very Good',3,41);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (842,3,'Good',88,42);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (843,1,'Very Good',23,43);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (844,5,'Good',6,44);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (845,3,'Very Good',23,45);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (846,4,'Excellent',80,46);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (847,1,'Excellent',82,47);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (848,1,'Very Good',88,48);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (849,4,'Very Bad',57,49);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (850,4,'Good',72,50);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (851,2,'Very Good',96,51);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (852,1,'Very Bad',77,52);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (853,3,'Very Good',93,53);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (854,5,'Very Good',63,54);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (855,4,'Average',83,55);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (856,2,'Bad',12,56);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (857,2,'Bad',2,57);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (858,5,'Very Good',95,58);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (859,4,'Good',58,59);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (860,5,'Very Bad',12,60);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (861,2,'Very Good',22,61);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (862,2,'Average',39,62);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (863,4,'Good',2,63);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (864,5,'Very Good',46,64);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (865,2,'Average',5,65);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (866,1,'Good',64,66);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (867,3,'Excellent',70,67);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (868,1,'Bad',89,68);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (869,4,'Very Bad',70,69);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (870,5,'Average',100,70);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (871,1,'Average',85,71);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (872,2,'Very Good',45,72);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (873,1,'Very Bad',80,73);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (874,2,'Excellent',95,74);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (875,4,'Good',48,75);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (876,5,'Good',17,76);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (877,5,'Very Bad',75,77);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (878,4,'Good',45,78);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (879,5,'Bad',85,79);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (880,4,'Bad',58,80);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (881,3,'Average',61,81);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (882,1,'Very Bad',24,82);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (883,5,'Very Good',18,83);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (884,2,'Very Good',33,84);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (885,1,'Very Bad',52,85);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (886,4,'Very Bad',95,86);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (887,2,'Good',63,87);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (888,2,'Excellent',64,88);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (889,3,'Average',14,89);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (890,4,'Bad',57,90);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (891,4,'Very Bad',94,91);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (892,2,'Very Good',19,92);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (893,1,'Excellent',32,93);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (894,4,'Good',9,94);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (895,4,'Average',18,95);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (896,3,'Good',30,96);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (897,1,'Very Bad',61,97);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (898,3,'Very Good',95,98);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (899,4,'Bad',8,99);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (900,1,'Very Good',92,100);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (901,3,'Bad',14,1);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (902,1,'Bad',39,2);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (903,5,'Excellent',70,3);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (904,5,'Good',66,4);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (905,3,'Bad',28,5);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (906,2,'Very Bad',45,6);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (907,4,'Very Bad',85,7);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (908,5,'Good',48,8);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (909,4,'Very Bad',30,9);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (910,3,'Excellent',81,10);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (911,2,'Very Good',13,11);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (912,1,'Excellent',37,12);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (913,1,'Very Good',49,13);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (914,2,'Bad',21,14);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (915,5,'Bad',24,15);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (916,4,'Good',6,16);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (917,4,'Average',59,17);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (918,2,'Very Bad',86,18);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (919,1,'Very Good',13,19);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (920,4,'Very Bad',76,20);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (921,2,'Good',34,21);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (922,5,'Very Bad',4,22);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (923,5,'Average',65,23);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (924,1,'Average',23,24);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (925,5,'Bad',42,25);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (926,1,'Very Bad',43,26);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (927,5,'Very Good',99,27);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (928,5,'Very Good',54,28);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (929,5,'Average',58,29);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (930,4,'Very Bad',87,30);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (931,3,'Very Bad',40,31);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (932,2,'Good',84,32);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (933,2,'Good',9,33);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (934,2,'Bad',26,34);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (935,4,'Excellent',74,35);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (936,4,'Excellent',88,36);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (937,2,'Average',6,37);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (938,4,'Good',66,38);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (939,3,'Very Bad',66,39);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (940,5,'Very Bad',78,40);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (941,1,'Very Good',29,41);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (942,2,'Average',78,42);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (943,5,'Average',21,43);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (944,1,'Very Bad',7,44);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (945,3,'Average',77,45);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (946,2,'Very Bad',10,46);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (947,5,'Good',88,47);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (948,2,'Very Bad',31,48);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (949,5,'Very Bad',14,49);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (950,5,'Very Bad',91,50);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (951,3,'Very Good',8,51);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (952,2,'Very Good',6,52);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (953,4,'Bad',24,53);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (954,1,'Good',84,54);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (955,5,'Very Bad',33,55);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (956,3,'Very Bad',80,56);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (957,4,'Average',46,57);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (958,2,'Average',12,58);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (959,5,'Very Bad',44,59);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (960,5,'Average',58,60);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (961,4,'Excellent',6,61);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (962,3,'Average',97,62);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (963,3,'Very Good',96,63);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (964,5,'Very Bad',3,64);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (965,5,'Very Good',38,65);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (966,5,'Very Good',19,66);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (967,1,'Average',5,67);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (968,4,'Very Bad',23,68);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (969,2,'Good',24,69);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (970,5,'Bad',2,70);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (971,3,'Excellent',63,71);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (972,3,'Excellent',4,72);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (973,1,'Bad',27,73);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (974,3,'Bad',52,74);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (975,2,'Very Bad',6,75);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (976,4,'Bad',98,76);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (977,2,'Excellent',9,77);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (978,5,'Very Bad',35,78);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (979,3,'Excellent',84,79);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (980,1,'Very Bad',97,80);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (981,2,'Bad',93,81);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (982,2,'Very Good',24,82);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (983,5,'Average',73,83);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (984,4,'Good',83,84);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (985,1,'Bad',74,85);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (986,5,'Bad',37,86);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (987,2,'Very Bad',96,87);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (988,1,'Average',79,88);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (989,5,'Excellent',3,89);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (990,4,'Bad',17,90);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (991,2,'Excellent',66,91);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (992,5,'Very Bad',74,92);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (993,1,'Very Bad',95,93);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (994,1,'Average',62,94);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (995,2,'Average',38,95);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (996,4,'Good',24,96);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (997,5,'Very Bad',9,97);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (998,2,'Very Bad',40,98);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (999,4,'Good',84,99);
INSERT INTO hotel_feedback(id,stars,review,cust_id,hotel_id) VALUES (1000,3,'Good',87,100);
